# Ubuntu 16.04 required for Python >= 3.7
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - make check
